version: '3'
services:
  webapp:
    build: .
    restart: always
    environment:
      DATABASE_HOST: $DATABASE_HOST
      DATABASE_PORT: $DATABASE_PORT
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_NAME: $DATABASE_NAME
    ports:
      - "5000:5000"
    depends_on:
      - postgres-common
    networks:
      - ournetwork
  postgres-common:
    container_name: postgres
    restart: always
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    ports:
      - "5432:5432"
    networks:
      - ournetwork
networks:
  ournetwork:
    driver: bridge